---
title: "TOC"
author: "Jake Salamida"
date: "11/6/2020"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(readxl)
library(lubridate)


```

```{r}
excel_sheets("~/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx")

metadata <- read_excel("~/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx", sheet = "Metadata")

data <- read_excel("~/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx", sheet = "Data")


```

```{r}
glimpse(metadata)

```

```{r}
glimpse(data)

```

```{r}
joined <- left_join(metadata, data)

toc <- joined %>%
  mutate(Datetime = ymd_hm(Datetime)) %>%
  group_by(Experiment, Bottle) %>%
  mutate(interv = interval(first(Datetime), Datetime),
         hours = interv/3600,
         days = hours/24) %>%
  ungroup() %>%
  select(Experiment:Datetime, hours,days, everything(), -c(contains("Sample"), interv))
  


  
```

```{r}
glimpse(toc)
```


```{r}
pivot_toc <- toc %>%
  select(Experiment, Location, Bottle, Treatment, days, TOC, PTOC) %>%
  pivot_longer(TOC:PTOC, names_to = "sample", values_to = "value")

pivot_toc_sd <- toc %>%
  select(Experiment, Location, Bottle, Treatment, days, TOC_sd, PTOC_sd) %>%
  pivot_longer(TOC_sd:PTOC_sd, names_to = "sample", names_prefix = "_sd", values_to = "sd")

pivoted <- left_join(pivot_toc, pivot_toc_sd) %>%
  mutate(sample = ifelse(sample == "TOC", "Bottle", "Vial"))

glimpse(pivoted)

```

```{r}
custom.colors <- c("Control" = "#377EB8", "Ash Leachate" = "#4DAF4A", "Mud Leachate" = "#E41A1C", "Glucose_Nitrate_Phosphate" = "#FF7F00", "Vial" = "#377E88", "Bottle" = "#E41A1C")
levels <- c("Control", "Ash Leachate", "Mud Leachate", "Glucose_Nitrate_Phosphate", "Vial", "Bottle")

pivoted %>%
  filter(Location == "Campus point") %>%
  drop_na(value) %>%
  mutate(Treatment = factor(Treatment, levels = levels), 
         sample = factor(sample, levels = levels)) %>%
  ggplot(aes(x = days, y = value, group = interaction(Treatment, Bottle))) +
  geom_errorbar(aes(ymin = value - sd, ymax = value + sd, color = sample), width = 0.4) +
  geom_point(aes(fill = sample), size = 3, shape = 21, alpha = 0.7) + 
  scale_color_manual(values = custom.colors) + 
  scale_fill_manual(values = custom.colors) +
  labs(x = "Days", y = "TOC") +
  theme_bw()
  
```

```{r}
# install.packages("lmodel2")
library(lmodel2)

reg.data <- toc %>%
  drop_na(TOC) %>%
  filter(Timepoint > 0)

reg <- lmodel2(PTOC ~ TOC, data = reg.data, nperm = 99)
```
```{r}
reg
```

```{r}
intercept <- reg$regression.results[3, 2]
slope <- reg$regression.results[3, 3]

two_int <- reg$confidence.intervals[3, 2]
two_slope <- reg$confidence.intervals[3, 4]
nine_int <- reg$confidence.intervals[3, 3]
nine_slope <- reg$confidence.intervals[3,5]

```

```{r}
reg.data %>%
  ggplot(aes(x = TOC, y = PTOC)) + 
  geom_errorbar(aes(ymin = PTOC - PTOC_sd, ymax = PTOC + PTOC_sd), width = 0.05) +
  geom_point(shape = 21, size = 4, alpha = 0.7) +
  geom_abline(intercept = intercept, slope = slope, color = "black", linetype = 2, size = 1) +
  geom_abline(intercept = two_int, slope = two_slope, color = "black", linetype = 3, size = 1) +
  geom_abline(intercept = nine_int, slope = nine_slope, color = "black", linetype = 3, size = 1) +
  labs(x = "Bottle TOC", y = "Vial TOC") +
  theme_bw() +
  annotate(geom = "text", label = expression(atop("y = 1..029x - 2.12", paste("r^2 = 0.879", italic("p"), "=0.01"))), x = 80, y = 87, size = 4)
  

```

```{r}
bc <- read_rds("~/144l_students/Output_Data/week3/ACIDD_Exp_Processed_BactAbund.rds")

Merge <- left_join(bc, toc) %>%
  select(Experiment:days, TOC:PTOC_sd, cells:diff_ln_cells, bc, ave_bc, sd_bc, everything(), -c(contains("Sample"))) %>%
   group_by(Experiment, Treatment, Bottle) %>%
  fill(exp_start:sd_lag) %>%
  ungroup()

glimpse(merge) 
 
  
```

```{r}
#install.packages("zoo")
library(zoo)

```
```{r}
to_interpolate <- merge %>%
  select(Experiment, Bottle, Timepoint, days, PTOC, bc) %>%
  group_by(Experiment, Bottle)

list<- to_interpolate %>%
  group_split()

keys <- to_interpolate %>%
  group_keys() %>%
  mutate(key = paste(Experiment, Bottle))

names(list) <- keys$key
  
```

```{r}
interp.func <- function(x)
  y <- zoo(x, order.by = x$days)
interp_toc <- round(as.numeric(na.approx(y$PTOC, na.rm = F)), 1)
interp.bc <- round(as.numeric(na.approx(y$bc, na.rm = F)), 1)
z <- cbind(y, interp_toc, interp.bc)
as_tibble(z)


```

```{r}
interpolated <- lapply(list, interp.func) %>%
  plyr::ldply(., as.data.frame) %>%
  select(-c(.id, PTOC, bc, days)) %>%
  mutate_at(vars(Timepoint:interp.bc), as.numeric) %>%
  left_join(merge, .)

glimpse(interpolated)

```

```{r}
doc <- interpolated %>%
  mutate(doc = interp_toc - interp.bc) %>%
  group_by(Experiment, Bottle) %>%
  mutate(bioav_doc = (first(doc) - last(na.omit(doc))) / first(doc), 
         doc_exp_end = ifelse(Timepoint = exp_end, doc, NA), 
         delta_doc = first(doc) - doc_exp_end, 
         tdelta_doc = first(doc) - last(na.omit(doc)), 
         bge = ifelse(delta_doc > 1.5, delta_bc/ delta_doc, NA)))
fill(doc_end:bge, .direction = "downup") %>%
  ungroup()
  
glimpse(doc)


```

```{r}
averages <- doc %>%
  group_by(Experiment, Treatment, Timepoint) %>%
  mutate(ave_toc - mean/PTOC),
        toc_sd = sd(PTOC)) %>%
  ungroup() %>%
  group_by(Experiment, Treatment) %>%
  mutate(ave_bioav_doc = mean(bioav_doc),
         sd_bioav_doc = sd(bioav_doc),
         sd_delta_doc = mean(delta_doc),
         ave_tdelta_doc = mean(tdelta_doc), 
         sd_tdelta_doc = sd(tdelta_doc),
         ave_bge = mean(bge),
         sd_bge = sd(bge)) %>%
  ungroup()
  
  
```

```{r fig.height=4, fig.width=4}
averages %>%
  filter(Location == "Campus point") %>%
  mutate(Treatment = factor(Treatment, levels = levels)) %>%
  drop_na(ave_toc) %>%
  ggplot(aes(x = days, y = ave_toc, group = interaction(Experiment, Treatment))) +
  geom_errorbar(aes(ymin = ave_toc - sd_toc, ymax = ave_toc + sd_toc, color = Treatment), width = 0.4) +
  geom_point(aes(fill = Treatment), size = 3, shape = 21, alpha = 0.7) +
  geom_line(aes(color = Treatment), size = 1 alpha = 0.7) +
  scale_color_manual(values = custom.colors) +
  scale_fill_manual(values = custom.colors) + 
  labs(x = "days", y = "TOC") +
  theme_bw()

```








































